CREATE DATABASE [TSQL]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TSQL', FILENAME = N'C:\TSQL\TSQL.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TSQL_log', FILENAME = N'C:\TSQL\TSQL_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [TSQL] SET RECOVERY SIMPLE 
GO